### ISSUE TITLE
Gizmo offset possible?

### ISSUE THREAD

**Issue by enzyme69** [Pullusb/storytools#1]
While testing this addon the first time, I found the gizmo button for the camera seems to be overlapping with another grease pencil related addon called NijiGPen, which I need to use both. 

Could we have a way to offset the buttons Gizmo?

![Screenshot 2023-05-26 at 9 10 09 am](https://github.com/Pullusb/storytools/assets/3952687/d7f5e9a1-725d-43a8-a825-68bfce8bbc07)

**Comment by Pullusb** [comment]
You will find that option in the addon preferences:
![storytools_ui_customizations](https://github.com/Pullusb/storytools/assets/7763187/4f90afc7-e667-4486-b379-83872cf2203f)
