### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Juke-Incorporated** [Pullusb/storytools#2]
Im getting a weird error when trying to enable the plugin? how can i fix this?
![stupiderror](https://github.com/Pullusb/storytools/assets/117942276/b9dc3864-e0a2-41be-bc33-3f57a92317f9)

**Comment by Pullusb** [comment]
Hi !

The plugin is not compatible with older version of Blender.
You should at least use 3.0
(older version the plugin was tested with is 3.3)
