### ISSUE TITLE
Custom camera creation operator

### ISSUE THREAD

**Issue by Pullusb** [Pullusb/storytools#28]
Add a custom camera creation operator
Will allow to choose to set as active or not
Allow creation even if current mode is not object

Should orient with view.
Should detect if there are any camera marker already existing in scene. and then allow use of marker

**Comment by Pullusb** [comment]
Done in commit ba1bb35e1af816d3f3b74134c6673e2053700db9

**Comment by Gattung** [comment]
Nice one, thx
