### ISSUE TITLE
Unable to Assign brush to shortcut

### ISSUE THREAD

**Issue by enlargedhousecats** [Pullusb/storytools#3]
![blender_1gink0Wx3y](https://github.com/Pullusb/storytools/assets/51523905/b2ddc0ed-8a77-46c7-a679-6855b5f71208)

On blender 3.3 and 4.0 when attempting to set a specific brush to a shortcut(like for example airbrush for the sketch layer and in pen for line layer) the addon returns the above error

**Comment by enlargedhousecats** [comment]
corretion, any change to any value in the shortcuts menu results in the error

**Comment by enlargedhousecats** [comment]
values still seem to be editable in the regular keymap editor however

**Comment by Pullusb** [comment]
Tx for the report, will look into it whenever I got time.

**Comment by Pullusb** [comment]
I pushed a fix (1.3.3 update)
Reopen the issue if you still have bug with the keymap display.
