### ISSUE TITLE
1/9/2024 Blender 4.1 build storytools crashes blender

### ISSUE THREAD

**Issue by Gattung** [Pullusb/storytools#4]
Hello, I just did a 4.1  Blender build for windows and found that when I try to use storytools Blender will crash to desktop.

Heres the error I getting on the crash when clicking on the storytools n-panel
```

ERROR (gpu.shader): GPU_material_compile VertShader:
      |
 3023 |     result = closure_eval(diffuse_data, reflection_data);
      |
      | gpu_shader_material_principled.glsl:290:0: Error: C1115: unable to find compatible overloaded function "closure_eval(struct ClosureSubsurface, struct ClosureReflection)"

ERROR (gpu.shader): GPU_material_compile FragShader:
      |
 3024 |     result = closure_eval(diffuse_data, reflection_data);
      |
      | gpu_shader_material_principled.glsl:290:0: Error: C1115: unable to find compatible overloaded function "closure_eval(struct ClosureSubsurface, struct ClosureReflection)"
```

**Comment by Gattung** [comment]
Nevermind, same thing is happening with machin3tools batch addon. Guess its a Blender thing.

**Comment by Pullusb** [comment]
Yeah probably a Blender thing.

As many devs, I always wait for a release version, or at least beta state, before updating my addons.
Otherwise it's like building the house on moving ground ^^.

Thank you for reporting anyway.
