### ISSUE TITLE
Attempting to make a change to the Drawtool shortcuts makes Shortcuts disappear, changed settings dont save

### ISSUE THREAD

**Issue by enlargedhousecats** [Pullusb/storytools#5]
![blender_MyHjxtrvaB](https://github.com/Pullusb/storytools/assets/51523905/1775eca9-0376-43e2-b7f6-560c4a88f60d)

When I try to change settings to the shortcuts for story tools the settings disappear and I get a message that says "error(see console)" though in neither the info pannel nor the console is there any information

![image](https://github.com/Pullusb/storytools/assets/51523905/b4fa50ae-1eb8-4131-9a1c-8db113ee8651)

additionally, the Set DrawTool shortcuts never save when reset in the keymap editor even when saving settings manually.

**Comment by Pullusb** [comment]
I don't have the error, tested on Linux Blender `4.0.2` and `3.6.5`.
What is your operating system and blender version ?

**Comment by enlargedhousecats** [comment]
using l blender 3.3 on windows 11
the error occurs on 4.0.2 and 3.6.5 as well

**Comment by Pullusb** [comment]
Can you screenshot or copy paste the console error (should start with `Traceback...`) ?
on windows you can open the console in `Blender top Menu > Windows > toggle Console`

**Comment by enlargedhousecats** [comment]
for some reason the error doesnt appear anymore after reinstalling the plugin to blender while blender is activated as administrator

**Comment by enlargedhousecats** [comment]
trying to recreate this issue by decativating administrator

**Comment by enlargedhousecats** [comment]
seems it just works now after installing when running as administrator, which is a cool solution for now though it begs the question what was going on before? I've been using the plugin for months without thinking to run as administrator so it would help somone else to know what was going on so that trick is never needed to make it work at full capacity

**Comment by enlargedhousecats** [comment]
how can I delete any trace of this addon in whatever folder must have gotten accessed by instaling as administrator so I could try to recreate the issue again?

**Comment by Pullusb** [comment]
This is weird... this addon does not install any third party package (yet), so running as admin or not shouldn't do anything different.

To make sure all trace of the addon are gone, simply remove "storytools" folder in your users addon folder.
On windows, it's located in your user addon folder in under appdata.
Something like this:

`C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons`

There is a nice (but long) one-liner you can paste and execute in interactive python console to open automatically this directory from blender:

`bpy.ops.wm.path_open(filepath=bpy.utils.user_resource('SCRIPTS', path='addons'))`

Like this
![image](https://github.com/Pullusb/storytools/assets/7763187/9210d1f7-316c-49d1-aab1-39f0344ed3f5)


Note: Using **install from file** is the same thing as unzipping in this directory.

Let me know how it went

**Comment by Pullusb** [comment]
Closing ticket
