### ISSUE TITLE
Error when trying to create New Drawing (refers to grease_pencils_v3)

### ISSUE THREAD

**Issue by SpitfireStoryboards** [Pullusb/storytools#61]
<img width="1280" alt="ScreenHunter 13140" src="https://github.com/user-attachments/assets/46cd18f5-a330-4859-a88a-c0b999d39b3a">
When trying to create a new GP from your plus utton in drawings tab, I get this error

**Comment by SpitfireStoryboards** [comment]
this is in 4.2.2. Ver 1.92.0 of addon

**Comment by SpitfireStoryboards** [comment]
happens in 4.0 too

**Comment by Pullusb** [comment]
hi, as stated in #62, new version are for Blender 4.3+
head to the release page. I'll fix the readme asap
